# Generated by Django 5.2 on 2025-08-21 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('median_home_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('median_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('price_trend', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rent_trend', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('unemployment_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('city', 'state')},
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('property_type', models.CharField(max_length=50)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('square_feet', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_assessment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('annual_taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rent_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('days_on_market', models.IntegerField(blank=True, null=True)),
                ('attom_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('zillow_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mls_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_api_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'state'], name='Dashboard_p_city_27fea5_idx'), models.Index(fields=['property_type'], name='Dashboard_p_propert_597902_idx'), models.Index(fields=['current_price'], name='Dashboard_p_current_1c09cb_idx'), models.Index(fields=['estimated_rent'], name='Dashboard_p_estimat_22661a_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvestmentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_rental_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('net_operating_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cap_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cash_on_cash_return', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estimated_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_to_rent_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('market_volatility', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('investment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('property_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='Dashboard.property')),
            ],
        ),
        migrations.CreateModel(
            name='UserWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'property_ref')},
            },
        ),
    ]
