# Generated by Django 5.2 on 2025-08-22 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentmetrics',
            name='profit_margin',
        ),
    ]
