# Generated by Django 5.2.5 on 2025-08-23 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_remove_profit_margin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fair_market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('annual_noi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('five_year_roi_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('monthly_gross_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annual_operating_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('annual_appreciation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('investment_recommendation', models.CharField(blank=True, max_length=500)),
                ('analysis_summary', models.TextField(blank=True)),
                ('key_assumptions', models.TextField(blank=True)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('valuation_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attom_endpoints_used', models.JSONField(blank=True, default=list)),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='Dashboard.property')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property_ref', '-created_at'], name='Dashboard_p_propert_22eefb_idx'), models.Index(fields=['valuation_successful'], name='Dashboard_p_valuati_d20a86_idx'), models.Index(fields=['fair_market_value'], name='Dashboard_p_fair_ma_765dbe_idx')],
            },
        ),
    ]
