# Generated by Django 5.2.5 on 2025-08-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_propertyvaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentmetrics',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
