# Generated by Django 5.2.5 on 2025-08-23 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_investmentmetrics_roi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('acquisition', 'Acquisition'), ('review', 'Review'), ('active', 'Active'), ('closed', 'Closed')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=15)),
                ('expected_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estimated_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('target_close_date', models.DateField(blank=True, null=True)),
                ('actual_close_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('property_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='Dashboard.property')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='Dashboard.dealstage')),
            ],
            options={
                'ordering': ['stage__order', 'position', '-created_at'],
                'indexes': [models.Index(fields=['stage', 'position'], name='Dashboard_d_stage_i_d83bc7_idx'), models.Index(fields=['created_by'], name='Dashboard_d_created_cc1a9c_idx'), models.Index(fields=['assigned_to'], name='Dashboard_d_assigne_e00091_idx'), models.Index(fields=['status'], name='Dashboard_d_status_d7d4cf_idx')],
            },
        ),
    ]
