# Generated by Django 5.2.5 on 2025-08-24 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_dealstage_deal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='deal_type',
            field=models.CharField(choices=[('rezoning', 'Rezoning'), ('distressed', 'Distressed'), ('arbitrage', 'Arbitrage'), ('flip', 'Fix & Flip'), ('rental', 'Buy & Hold Rental'), ('development', 'Development'), ('wholesale', 'Wholesale'), ('brrr', 'BRRR (Buy, Rehab, Rent, Refinance)'), ('commercial', 'Commercial'), ('land', 'Land Banking'), ('other', 'Other')], default='other', help_text='Automatically categorized using AI, can be manually overridden', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['deal_type'], name='Dashboard_d_deal_ty_276d54_idx'),
        ),
    ]
