# Generated by Django 5.2.5 on 2025-08-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_deal_deal_type_deal_dashboard_d_deal_ty_276d54_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_type',
            field=models.CharField(choices=[('rezoning', 'Rezoning'), ('distressed', 'Distressed'), ('arbitrage', 'Arbitrage'), ('flip', 'Fix & Flip'), ('rental', 'Buy & Hold Rental'), ('development', 'Development'), ('wholesale', 'Wholesale'), ('brrr', 'BRRR (Buy, Rehab, Rent, Refinance)'), ('commercial', 'Commercial'), ('land', 'Land Banking'), ('other', 'Other')], default='other', help_text='Deal type category - select the most appropriate option', max_length=20),
        ),
    ]
