# Generated by Django 5.2.5 on 2025-08-25 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_alter_deal_deal_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_properties', models.IntegerField(default=0)),
                ('total_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_equity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('portfolio_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_appreciation', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('appreciation_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('monthly_cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cash_on_cash_return', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_return_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('portfolio_cap_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('diversification_score', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_metrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOwnedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_address', models.CharField(blank=True, max_length=500)),
                ('custom_city', models.CharField(blank=True, max_length=100)),
                ('custom_state', models.CharField(blank=True, max_length=50)),
                ('custom_zip_code', models.CharField(blank=True, max_length=20)),
                ('custom_property_type', models.CharField(blank=True, max_length=50)),
                ('custom_bedrooms', models.IntegerField(blank=True, null=True)),
                ('custom_bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('custom_square_feet', models.IntegerField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_date', models.DateField()),
                ('down_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('loan_term_years', models.IntegerField(blank=True, null=True)),
                ('current_estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_valuation_date', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property_manager', models.CharField(blank=True, max_length=200)),
                ('management_fee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('status', models.CharField(choices=[('owned', 'Owned'), ('rented', 'Rented Out'), ('vacant', 'Vacant'), ('selling', 'For Sale'), ('sold', 'Sold')], default='owned', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashboard.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('rent', 'Rent Payment'), ('late_fee', 'Late Fee'), ('pet_fee', 'Pet Fee'), ('other_income', 'Other Income'), ('mortgage', 'Mortgage Payment'), ('insurance', 'Insurance'), ('taxes', 'Property Taxes'), ('maintenance', 'Maintenance & Repairs'), ('utilities', 'Utilities'), ('management', 'Property Management'), ('advertising', 'Advertising/Marketing'), ('legal', 'Legal Fees'), ('hoa', 'HOA Fees'), ('vacancy', 'Vacancy Loss'), ('other_expense', 'Other Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('receipt_uploaded', models.BooleanField(default=False)),
                ('receipt_file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owned_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Dashboard.userownedproperty')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='userownedproperty',
            index=models.Index(fields=['user', 'status'], name='Dashboard_u_user_id_9851aa_idx'),
        ),
        migrations.AddIndex(
            model_name='userownedproperty',
            index=models.Index(fields=['purchase_date'], name='Dashboard_u_purchas_86618f_idx'),
        ),
        migrations.AddIndex(
            model_name='rentaltransaction',
            index=models.Index(fields=['owned_property', 'transaction_type'], name='Dashboard_r_owned_p_50ba3a_idx'),
        ),
        migrations.AddIndex(
            model_name='rentaltransaction',
            index=models.Index(fields=['date'], name='Dashboard_r_date_54faf1_idx'),
        ),
        migrations.AddIndex(
            model_name='rentaltransaction',
            index=models.Index(fields=['category'], name='Dashboard_r_categor_0838b0_idx'),
        ),
    ]
